### ISSUE TITLE
Cannot find 'Process' in scope

### ISSUE THREAD

**Issue by Abanoub-Ghaly** [aydenp/PassEncoder#13]
<img width="698" alt="Screen Shot 2022-05-26 at 5 35 07 PM" src="https://user-images.githubusercontent.com/104997275/170522162-174b13c4-a866-4669-9b63-1af81eed02f2.png">

**Comment by sushil-tiwari-1kosmos** [comment]
Any update on above issue?

**Comment by aydenp** [comment]
What OS are you building for when this occurs? What's the deployment target?

**Comment by sushil-tiwari-1kosmos** [comment]
@aydenp  Kindly ignore it. The OS selected was iOS which I figured out later.

**Comment by aydenp** [comment]
Thanks, that would make this one #8
