### ISSUE TITLE
encoder fail under ubuntu

### ISSUE THREAD

**Issue by ormaa** [aydenp/PassEncoder#2]
Hello,
not sure it is an issue, or a limitation : 

this package seem to not working properly under Ubuntu.
is it a mistake in my code + configuration ? 
or is it a limitation from apple, which request to have a MAC under MACOS to sign the json wallet pass ?

if it is a bug : then, I can send details, configuration, and code.

thanks

**Comment by aydenp** [comment]
Could you include code examples, configuration, and errors so that I could take a look and see what the problem likely is?

**Comment by ormaa** [comment]
Hello.

here is a zip file containing a copy of my project files
[test (copy).zip](https://github.com/aydenp/PassEncoder/files/3835326/test.copy.zip)

**Comment by ormaa** [comment]
my configuration : 
Ubuntu 16.04, 
Swift 5.0.1

no error thrown, just this return nil : 
if let encoder = PassEncoder(passDataURL:  directory) {
directory, on my computer : 
/home/server/Desktop/test/OrmaaCard.pass/pass.json

**Comment by aydenp** [comment]
How do you create `directory`?

**Comment by ormaa** [comment]
Hello,

I use this line to create “directory” variable :
let directory = URL(string: FileManager.default.currentDirectoryPath + “/OrmaaCard.pass/pass.json"<="" span="">)!
<="" span="">

**Comment by aydenp** [comment]
I didn’t see your ZIP at first, sorry. Could you try initializing the URL with [URL(fileURLWithPath:)](https://developer.apple.com/documentation/foundation/url/3126800-init)?

**Comment by ormaa** [comment]
Thanks for the help, it works now

Encoder do the job properluy

I obtain my pkpass, I just need now to test if it is recognised properly.
I will close my issue.

thanks
