### ISSUE TITLE
Wrong Requirements

### ISSUE THREAD

**Issue by JoaoCPires** [aydenp/PassEncoder#7]
On the ReadMe, the requirements are 'iOS 10.0+ / macOS 10.12+ / tvOS 10.0+ / watchOS 3.0+'

In fact, this cannot run on anything other than macOS.
The Process object, used to sign the Pass Manifest, can't be used on anything other than macOS, as seen [here](https://developer.apple.com/documentation/foundation/process)

**Comment by aydenp** [comment]
Thank you for opening this! I'm going to merge this into #8 as its a bit more descriptive.
